[package]
name = "lab3-rust"
version = "0.1.0"
authors = ["Jakub DÄ…bek <jakub.dabek@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
lalrpop = "0.17.2"

[dependencies]
lalrpop-util = "0.17.2"
regex = "1"
num = "*"
